import { StyleSheet } from 'react-native';

import { GameColors, GameFonts, fillParent } from '@/constants/gameTheme';

/** Every style for GameScreen and the small components it composes. */
export const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: '#1E8CFF' },
  backdrop: {
    ...fillParent,
    zIndex: 0,
  },
  backdropImage: {
    width: '100%',
    height: '100%',
  },
  hitLayer: {
    ...fillParent,
    zIndex: 20,
  },
  content: {
    ...fillParent,
    paddingHorizontal: 20,
    zIndex: 30,
    elevation: 30,
  },
  topBlock: {
    width: '100%',
    gap: 6,
  },
  topRow: {
    width: '100%',
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 10,
    minHeight: 40,
  },
  topLeft: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingRight: 4,
  },
  logoHud: {
    width: 104,
    height: 66,
    marginLeft: -4,
  },
  bottomBar: {
    position: 'absolute',
    left: 16,
    right: 16,
    zIndex: 45,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  menuBtn: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: GameColors.playBlue,
    borderWidth: 2.5,
    borderColor: GameColors.ink,
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  bestPill: {
    paddingHorizontal: 12,
    paddingVertical: 5,
    borderRadius: 14,
    borderWidth: 2.5,
    borderColor: GameColors.ink,
    backgroundColor: '#FFF4C2',
    alignItems: 'center',
    minWidth: 64,
    flexShrink: 0,
  },
  bestPillHot: {
    backgroundColor: GameColors.lemon,
  },
  bestLabel: {
    fontFamily: GameFonts.soft,
    fontSize: 12,
    color: GameColors.panelInk,
  },
  bestLabelHot: {
    fontFamily: GameFonts.body,
    color: GameColors.ink,
    letterSpacing: 0.4,
  },
  bestValue: {
    fontFamily: GameFonts.body,
    fontSize: 20,
    lineHeight: 24,
    color: GameColors.ink,
  },
  bestValueHot: {
    fontFamily: GameFonts.display,
  },
  // Home-screen score module — dominant BEST over a shorter tinted Daily.
  scoreModule: {
    width: 122,
    flexShrink: 0,
    borderRadius: 15,
    borderWidth: 2.5,
    borderColor: GameColors.ink,
    backgroundColor: '#FBEFBE',
    overflow: 'hidden',
  },
  scoreMain: {
    paddingHorizontal: 10,
    paddingTop: 7,
    paddingBottom: 8,
    gap: 3,
    alignItems: 'stretch',
  },
  scoreSectionPressed: {
    backgroundColor: 'rgba(26,28,44,0.06)',
  },
  scoreMainHead: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
  },
  trophyIcon: {
    width: 24,
    height: 24,
  },
  scoreBestLabel: {
    fontFamily: GameFonts.display,
    fontSize: 13,
    lineHeight: 16,
    color: GameColors.ink,
    letterSpacing: 0.4,
  },
  scoreBestValue: {
    fontFamily: GameFonts.display,
    fontSize: 24,
    color: GameColors.ink,
    letterSpacing: -0.5,
  },
  scoreLevelPill: {
    marginTop: 1,
    borderRadius: 10,
    paddingVertical: 3.5,
    paddingHorizontal: 8,
    alignItems: 'center',
    backgroundColor: GameColors.lemon,
  },
  scoreLevelText: {
    fontFamily: GameFonts.body,
    fontSize: 12,
    lineHeight: 15,
    color: GameColors.ink,
  },
  scoreDivider: {
    height: 2.5,
    backgroundColor: GameColors.ink,
  },
  scoreDaily: {
    paddingHorizontal: 10,
    paddingTop: 5,
    paddingBottom: 6,
    gap: 1,
    alignItems: 'flex-start',
    backgroundColor: 'rgba(88,204,2,0.18)',
  },
  scoreDailyLabel: {
    fontFamily: GameFonts.body,
    fontSize: 10,
    letterSpacing: 0.5,
    color: GameColors.bubbleDark,
  },
  scoreDailyRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  scoreDailyValue: {
    fontFamily: GameFonts.display,
    fontSize: 16,
    lineHeight: 19,
    color: GameColors.ink,
  },
  scoreDailyEmpty: {
    fontFamily: GameFonts.body,
    fontSize: 12,
    color: GameColors.bubbleDark,
  },
  // Results screen — best/difference summary + NEW BEST trophy.
  resultTrophy: {
    width: 64,
    height: 64,
  },
  resultSummary: {
    backgroundColor: 'rgba(255,255,255,0.94)',
    borderRadius: 16,
    borderWidth: 2.5,
    borderColor: GameColors.ink,
    paddingHorizontal: 16,
    paddingVertical: 10,
    alignItems: 'center',
    gap: 2,
    minWidth: 168,
  },
  resultSummaryLabel: {
    fontFamily: GameFonts.soft,
    fontSize: 12,
    letterSpacing: 0.6,
    color: GameColors.panelInk,
  },
  resultSummaryValue: {
    fontFamily: GameFonts.display,
    fontSize: 24,
    lineHeight: 28,
    color: GameColors.ink,
  },
  resultBestRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  resultGap: {
    fontFamily: GameFonts.body,
    fontSize: 14,
    color: GameColors.scoreBad,
    marginTop: 2,
  },
  statsBlock: { marginTop: 2, alignItems: 'center' },
  heartsAboveScore: {
    marginBottom: 6,
    alignItems: 'center',
  },
  bigScore: {
    fontFamily: GameFonts.display,
    fontSize: 52,
    lineHeight: 56,
    color: GameColors.white,
    textShadowColor: 'rgba(26,28,44,0.4)',
    textShadowOffset: { width: 0, height: 3 },
    textShadowRadius: 0,
  },
  bigScoreHot: {
    color: GameColors.lemon,
    textShadowColor: GameColors.ink,
    textShadowOffset: { width: 0, height: 3 },
    textShadowRadius: 0,
  },
  metaLine: {
    fontFamily: GameFonts.display,
    fontSize: 22,
    lineHeight: 26,
    color: GameColors.ink,
  },
  tapHowTo: {
    marginTop: 6,
    maxWidth: 260,
    fontFamily: GameFonts.body,
    fontSize: 15,
    lineHeight: 19,
    textAlign: 'center',
    color: 'rgba(255,255,255,0.7)',
    textShadowColor: 'rgba(26,28,44,0.35)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 0,
  },
  newBestTag: {
    marginTop: 4,
    fontFamily: GameFonts.display,
    fontSize: 18,
    lineHeight: 22,
    letterSpacing: 1,
    color: GameColors.lemon,
    textShadowColor: GameColors.ink,
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 0,
  },
  runStats: {
    marginTop: 8,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.94)',
    borderRadius: 16,
    borderWidth: 2.5,
    borderColor: GameColors.ink,
    paddingHorizontal: 14,
    paddingVertical: 8,
    gap: 12,
  },
  runStat: {
    alignItems: 'center',
    minWidth: 52,
  },
  runStatLabel: {
    fontFamily: GameFonts.soft,
    fontSize: 11,
    color: GameColors.panelInk,
    letterSpacing: 0.6,
  },
  runStatValue: {
    fontFamily: GameFonts.display,
    fontSize: 20,
    lineHeight: 24,
    color: GameColors.ink,
  },
  runStatDivider: {
    width: 2,
    height: 28,
    borderRadius: 1,
    backgroundColor: 'rgba(26,28,44,0.15)',
  },
  comboFloat: {
    position: 'absolute',
    left: 0,
    right: 0,
    alignItems: 'center',
    zIndex: 30,
  },
  comboFloatLabel: {
    fontFamily: GameFonts.display,
    fontSize: 14,
    lineHeight: 16,
    letterSpacing: 2,
    color: GameColors.white,
    textAlign: 'center',
    textShadowColor: GameColors.ink,
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 0,
  },
  comboFloatValue: {
    fontFamily: GameFonts.display,
    fontSize: 52,
    lineHeight: 56,
    color: '#FFE96A',
    textAlign: 'center',
    textShadowColor: GameColors.ink,
    textShadowOffset: { width: 0, height: 4 },
    textShadowRadius: 0,
  },
  meterAnchor: {
    position: 'absolute',
    left: 0,
    right: 0,
    alignItems: 'center',
    justifyContent: 'flex-end',
    zIndex: 1,
  },
  meterDimmed: {
    opacity: 0.28,
  },
  hidden: { opacity: 0 },
  gameOverPanel: {
    ...fillParent,
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 40,
    gap: 18,
    paddingHorizontal: 24,
  },
  gameOverActions: {
    width: '100%',
    alignItems: 'center',
    gap: 12,
  },
  gameOverTitle: {
    fontFamily: GameFonts.display,
    fontSize: 52,
    lineHeight: 56,
    textAlign: 'center',
    color: '#FF4B4B',
    textShadowColor: GameColors.ink,
    textShadowOffset: { width: 0, height: 4 },
    textShadowRadius: 0,
  },
  gameOverTitleBest: {
    color: GameColors.lemon,
  },
  dailyShareDate: {
    fontFamily: GameFonts.body,
    fontSize: 18,
    lineHeight: 22,
    textAlign: 'center',
    color: GameColors.white,
    textShadowColor: 'rgba(26,28,44,0.45)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 0,
    marginBottom: -4,
  },
  feedback: {
    position: 'absolute',
    zIndex: 35,
    maxWidth: '52%',
  },
  feedbackAlignStart: { textAlign: 'left' },
  feedbackAlignEnd: { textAlign: 'right' },
  feedbackLabel: {
    fontFamily: GameFonts.display,
    fontSize: 28,
    lineHeight: 32,
    textShadowColor: GameColors.ink,
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 0,
  },
  feedbackLabelGreat: {
    fontSize: 44,
    lineHeight: 48,
    letterSpacing: 0.5,
    textShadowOffset: { width: 0, height: 3 },
  },
  feedbackPoints: {
    marginTop: 2,
    fontFamily: GameFonts.body,
    fontSize: 18,
    color: GameColors.white,
    textShadowColor: GameColors.ink,
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 0,
  },
  feedbackCombo: {
    marginTop: 3,
    fontFamily: GameFonts.display,
    fontSize: 18,
    lineHeight: 22,
    color: GameColors.lemon,
    textShadowColor: GameColors.ink,
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 0,
  },
  menuCol: {
    position: 'absolute',
    left: 28,
    right: 28,
    gap: 10,
    zIndex: 40,
    alignItems: 'center',
  },
  ctaPressable: {
    width: '100%',
    maxWidth: 320,
  },
  ctaPressableDown: {
    transform: [{ scale: 0.97 }],
  },
  ctaShell: {
    borderRadius: 22,
    borderWidth: 4,
    borderColor: GameColors.ink,
    overflow: 'hidden',
  },
  ctaFace: {
    minHeight: 64,
    paddingHorizontal: 20,
    paddingTop: 10,
    paddingBottom: 12,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  ctaFaceUp: {
    marginBottom: 5,
    borderBottomWidth: 0,
  },
  ctaFaceDown: {
    marginBottom: 0,
    marginTop: 5,
  },
  ctaShine: {
    position: 'absolute',
    left: 10,
    right: 10,
    top: 6,
    height: 14,
    borderRadius: 10,
    backgroundColor: 'rgba(255,255,255,0.28)',
  },
  ctaText: {
    fontFamily: GameFonts.display,
    fontSize: 30,
    lineHeight: 34,
    color: GameColors.white,
    letterSpacing: 1.5,
    textShadowColor: 'rgba(26,28,44,0.35)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 0,
  },
  ctaSub: {
    marginTop: 1,
    fontFamily: GameFonts.soft,
    fontSize: 12,
    lineHeight: 14,
    color: 'rgba(255,255,255,0.92)',
    letterSpacing: 0.8,
  },
  // Compact daily CTA — same row as the menu button, smaller than PLAY.
  secondaryCtaPressable: {
    flexShrink: 1,
  },
  secondaryCtaShell: {
    borderRadius: 16,
    borderWidth: 3,
    borderColor: GameColors.ink,
    overflow: 'hidden',
  },
  secondaryCtaFace: {
    minHeight: 36,
    paddingHorizontal: 14,
    paddingTop: 6,
    paddingBottom: 7,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: GameColors.bubble,
  },
  secondaryCtaFaceUp: {
    marginBottom: 3,
  },
  secondaryCtaFaceDown: {
    marginBottom: 0,
    marginTop: 3,
  },
  secondaryCtaLabel: {
    fontFamily: GameFonts.display,
    fontSize: 15,
    lineHeight: 18,
    color: GameColors.white,
    letterSpacing: 0.2,
    textShadowColor: 'rgba(26,28,44,0.35)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 0,
  },
});
