import { StyleSheet } from 'react-native';

import { GameColors, GameFonts } from '@/constants/gameTheme';

/** Every style for MenuSheet and the rows it composes. */
export const styles = StyleSheet.create({
  overlayRoot: {
    flex: 1,
  },
  overlay: {
    flex: 1,
    justifyContent: 'flex-end',
    backgroundColor: 'rgba(26,28,44,0.5)',
  },
  // Static until Reanimated binds — prevents a one-frame fully-opaque flash.
  overlayHidden: {
    opacity: 0,
  },
  dismissArea: {
    flex: 1,
  },
  sheet: {
    backgroundColor: '#E8F7FF',
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    borderTopWidth: 3,
    borderLeftWidth: 3,
    borderRightWidth: 3,
    borderColor: GameColors.ink,
    paddingHorizontal: 20,
    paddingTop: 6,
    gap: 18,
  },
  handleHit: {
    alignItems: 'center',
    paddingVertical: 10,
  },
  handle: {
    width: 52,
    height: 6,
    borderRadius: 3,
    backgroundColor: 'rgba(26,28,44,0.22)',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 4,
    gap: 8,
  },
  title: {
    flex: 1,
    fontFamily: GameFonts.display,
    fontSize: 30,
    lineHeight: 34,
    color: GameColors.ink,
  },
  titleRoot: {
    fontSize: 34,
    lineHeight: 38,
  },
  backBtn: {
    width: 44,
    height: 44,
    borderRadius: 14,
    backgroundColor: GameColors.white,
    borderWidth: 2.5,
    borderColor: GameColors.ink,
    alignItems: 'center',
    justifyContent: 'center',
  },
  backBtnText: {
    fontFamily: GameFonts.display,
    fontSize: 32,
    lineHeight: 34,
    color: GameColors.ink,
    marginTop: -2,
  },
  closeBtn: {
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 12,
    backgroundColor: GameColors.playBlue,
    borderWidth: 2.5,
    borderColor: GameColors.ink,
  },
  closeBtnPressed: {
    transform: [{ translateY: 2 }],
  },
  closeBtnText: {
    fontFamily: GameFonts.body,
    fontSize: 13,
    color: GameColors.white,
  },
  startOverBtn: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderRadius: 14,
    backgroundColor: GameColors.playBlue,
    borderWidth: 2.5,
    borderColor: GameColors.ink,
  },
  startOverBtnText: {
    fontFamily: GameFonts.body,
    fontSize: 18,
    color: GameColors.white,
  },
  body: {
    flex: 1,
    gap: 16,
  },
  menuScroll: {
    flex: 1,
  },
  menuScrollContent: {
    gap: 16,
    paddingBottom: 4,
  },
  supportCard: {
    borderRadius: 20,
    borderWidth: 2.5,
    borderColor: GameColors.ink,
    paddingHorizontal: 18,
    paddingTop: 18,
    paddingBottom: 16,
    gap: 10,
    overflow: 'hidden',
  },
  supportTitle: {
    fontFamily: GameFonts.display,
    fontSize: 22,
    lineHeight: 26,
    color: GameColors.white,
  },
  supportBody: {
    fontFamily: GameFonts.soft,
    fontSize: 15,
    lineHeight: 20,
    color: 'rgba(255,255,255,0.92)',
  },
  supportActions: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 4,
  },
  supportBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingVertical: 12,
    borderRadius: 999,
    backgroundColor: 'rgba(255,255,255,0.22)',
    borderWidth: 2,
    borderColor: 'rgba(255,255,255,0.35)',
  },
  supportBtnPressed: {
    transform: [{ translateY: 1 }],
    backgroundColor: 'rgba(255,255,255,0.3)',
  },
  supportBtnText: {
    fontFamily: GameFonts.body,
    fontSize: 16,
    lineHeight: 20,
    color: GameColors.white,
  },
  card: {
    backgroundColor: GameColors.white,
    borderRadius: 18,
    borderWidth: 2.5,
    borderColor: GameColors.ink,
    overflow: 'hidden',
  },
  row: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 18,
    paddingVertical: 18,
    gap: 12,
  },
  infoBlock: {
    paddingHorizontal: 18,
    paddingVertical: 18,
    gap: 6,
  },
  rowSelected: {
    backgroundColor: 'rgba(28,176,246,0.14)',
  },
  rowPressed: {
    backgroundColor: 'rgba(28,176,246,0.12)',
  },
  rowText: {
    flex: 1,
    gap: 3,
  },
  rowLabel: {
    fontFamily: GameFonts.body,
    fontSize: 20,
    lineHeight: 24,
    color: GameColors.ink,
  },
  rowLabelDanger: {
    color: GameColors.scoreBad,
  },
  rowSub: {
    fontFamily: GameFonts.soft,
    fontSize: 14,
    lineHeight: 18,
    color: GameColors.panelInk,
  },
  hsScroll: {
    flex: 1,
  },
  hsList: {
    gap: 14,
    paddingBottom: 8,
  },
  hsCapture: {
    backgroundColor: '#E8F7FF',
    borderRadius: 24,
    gap: 12,
    alignItems: 'center',
  },
  hsCaptureShot: {
    paddingHorizontal: 20,
    paddingVertical: 20,
  },
  hsLogo: {
    width: 118,
    height: 76,
  },
  hsShell: {
    alignSelf: 'stretch',
    borderRadius: 22,
    borderWidth: 2.5,
    borderColor: GameColors.ink,
    paddingBottom: 5,
  },
  hsFace: {
    borderRadius: 19,
    borderWidth: 2.5,
    borderColor: GameColors.ink,
    paddingHorizontal: 18,
    paddingTop: 14,
    paddingBottom: 16,
    gap: 8,
    overflow: 'hidden',
  },
  hsShine: {
    position: 'absolute',
    top: 0,
    left: 12,
    right: 12,
    height: 10,
    borderBottomLeftRadius: 12,
    borderBottomRightRadius: 12,
    backgroundColor: 'rgba(255,255,255,0.35)',
  },
  hsBadge: {
    alignSelf: 'flex-start',
    backgroundColor: GameColors.white,
    borderRadius: 12,
    borderWidth: 2.5,
    borderColor: GameColors.ink,
    paddingHorizontal: 12,
    paddingVertical: 5,
  },
  hsTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  hsShareBtn: {
    width: 36,
    height: 36,
    borderRadius: 12,
    backgroundColor: GameColors.white,
    borderWidth: 2.5,
    borderColor: GameColors.ink,
    alignItems: 'center',
    justifyContent: 'center',
  },
  hsBadgeText: {
    fontFamily: GameFonts.body,
    fontSize: 14,
    lineHeight: 18,
    color: GameColors.ink,
    letterSpacing: 0.6,
  },
  hsScore: {
    fontFamily: GameFonts.display,
    fontSize: 56,
    lineHeight: 60,
    color: GameColors.ink,
    marginTop: 2,
  },
  hsEmptyBlock: {
    gap: 4,
    paddingVertical: 4,
  },
  hsEmptyScore: {
    fontFamily: GameFonts.display,
    fontSize: 48,
    lineHeight: 52,
    color: 'rgba(26,28,44,0.35)',
  },
  hsEmptyHint: {
    fontFamily: GameFonts.soft,
    fontSize: 15,
    lineHeight: 20,
    color: GameColors.ink,
    maxWidth: '92%',
  },
  hsFooter: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginTop: 2,
  },
  hsLevelPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: GameColors.white,
    borderRadius: 12,
    borderWidth: 2.5,
    borderColor: GameColors.ink,
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  hsLevelLabel: {
    fontFamily: GameFonts.soft,
    fontSize: 12,
    lineHeight: 14,
    color: GameColors.panelInk,
  },
  hsLevelValue: {
    fontFamily: GameFonts.body,
    fontSize: 16,
    lineHeight: 18,
    color: GameColors.ink,
  },
  hsMeta: {
    fontFamily: GameFonts.body,
    fontSize: 15,
    lineHeight: 18,
    color: GameColors.ink,
  },
  selectedMark: {
    fontFamily: GameFonts.display,
    fontSize: 24,
    lineHeight: 28,
    color: GameColors.playBlue,
  },
  toggle: {
    minWidth: 58,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 12,
    borderWidth: 2.5,
    borderColor: GameColors.ink,
    alignItems: 'center',
  },
  toggleOn: {
    backgroundColor: GameColors.bubble,
  },
  toggleOff: {
    backgroundColor: '#D1D5DB',
  },
  toggleText: {
    fontFamily: GameFonts.body,
    fontSize: 14,
    color: GameColors.ink,
  },
  chevron: {
    fontFamily: GameFonts.display,
    fontSize: 30,
    lineHeight: 32,
    color: GameColors.ink,
    marginTop: -2,
  },
  divider: {
    height: 2,
    backgroundColor: 'rgba(26,28,44,0.08)',
    marginHorizontal: 18,
  },
  version: {
    fontFamily: GameFonts.soft,
    fontSize: 13,
    textAlign: 'center',
    color: GameColors.panelInk,
    marginTop: 'auto',
  },
});
