// https://docs.expo.dev/guides/using-eslint/
const { defineConfig } = require('eslint/config');
const expoConfig = require("eslint-config-expo/flat");

module.exports = defineConfig([
  expoConfig,
  {
    // `.astro/` is generated by the website build; `dist/` is build output.
    ignores: ["dist/*", "website/.astro/*", "website/dist/*"],
  }
]);
